### GET api/notes
GET http://localhost:3001/api/notes

### POST /api/pay
POST http://localhost:3001/api/pay
Content-Type: application/json

{
  "idc": "399754",
  "idf": "403140",
  "total": 4.50,
  "company": "EMPRESA CARNICA SANCTI SPIRITUS"
}

### POST /api/pay
POST http://localhost:3001/api/pay
Content-Type: application/json

{
  "idc": "sdfsdfsdf",
  "idf": "sdfsdfsdf",
  "total": 500.10101011,
  "company": "sdfsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfdsf"
}

