### GET home
GET http://localhost:3001/api

### POST /api/pay
POST http://localhost:3001/api/pay
Content-Type: application/json

{
  "idc": "399754",
  "idf": "403140",
  "total": 4.50,
  "company": "EMPRESA CARNICA SANCTI SPIRITUS"
}

### POST /api/muhia/stripe
POST http://localhost:3001/api/muhia/stripe
Content-Type: application/json

{
  "total": 4.50,
  "successUrl": "https://iracuba.com/",
  "cancelUrl": "https://iracuba.com/"
}

### POST /api/pay
POST http://localhost:3001/api/pay
Content-Type: application/json

{
  "idc": "sdfsdfsdf",
  "idf": "sdfsdfsdf",
  "total": 500.10101011,
  "company": "sdfsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfdsf"
}

### POST /api/stripe-webhook 
POST http://localhost:3001/api/stripe-webhook
Content-Type: application/json


